version: '3.8'

services:
  backend-file-validation:
    # build:
    #   context: ./backend
    #   dockerfile: Dockerfile
    image: carlosrb1/backend-file-validation:latest
    ports:
      - "5000:5000"
    networks:
      - file-validation-network
    container_name: backend-file-validation


  ganache-file-validation:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.ganache
    image: carlosrb1/ganache-file-validation:latest
    ports:
      - "7545:7545"
    #command: ganache-cli -p 7545 -h 0.0.0.0 -a 10 -e 100
    networks:
      - file-validation-network
    container_name: ganache-file-validation

  truffle-file-validation:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.truffle
    image: carlosrb1/truffle-file-validation:latest
    depends_on:
      - ganache-file-validation
      - backend-file-validation
    environment:
      - GANACHE_HOST=ganache-file-validation
      - GANACHE_PORT=7545
    networks:
      - file-validation-network
    ports:
      - "3001:3001"
      - "3000:3000"
    container_name: truffle-file-validation

networks:
  file-validation-network:
    driver: bridge
