version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: backend-container
    networks:
      - app-network

  ganache:
    #image: trufflesuite/ganache-cli
    build:
      context: .
      dockerfile: Dockerfile.ganache
    ports:
      - "7545:7545"
    #command: ganache-cli -p 7545 -h 0.0.0.0 -a 10 -e 100
    networks:
      - app-network
    container_name: ganache-container

  truffle:
    build:
      context: .
      dockerfile: Dockerfile.truffle
    depends_on:
      - ganache
      - backend
    environment:
      - GANACHE_HOST=ganache
      - GANACHE_PORT=7545
    networks:
      - app-network
    ports:
      - "3001:3001"
      - "3000:3000"
    container_name: truffle-container

networks:
  app-network:
    driver: bridge
